# FRP服务端
# frp监听的端口和ip
bindPort = 7000
bindAddr = '0.0.0.0'
kcpBindPort = 7000

# frp管理后台端口
webServer.addr = "0.0.0.0"
webServer.port = 7001
# frp管理后台用户名和密码
webServer.user = "musdrop"
webServer.password = "233333"

# frp日志配置
log.to = "./frps.log"
# trace, debug, info, warn, error
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false


# 客户端验证方式
auth.method = "token"
auth.token = "233333"